package com.oauth.security.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.validation.constraints.NotBlank;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;
import lombok.ToString;

@Document(collection = "facebook_console")
@lombok.Data
@ToString
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class FacebookConsole implements Serializable {
	/**
	* 
	*/
	private static final long serialVersionUID = -3651545005709543986L;
	/**
	 * Id of the FacebookConsole. Unique Id generated by the mongoDB.
	 * 
	 * @return id
	 **/
	@ApiModelProperty(value = "Id of the FacebookConsole", example = "608bfb4e1b89300008af4b76")
	@Id
	private String id;

	/**
	 * Facebook console updated at.
	 * 
	 * @return updatedDate
	 **/
	@ApiModelProperty(value = "ProductId of the FacebookConsole", example = "608bfb4e1b89300008af4b76")
	@JsonProperty("productId")
	@Field("productId")
	@Indexed
	@NotBlank
	private String productId;

	/**
	 * Facebook console app id.
	 * 
	 * @return facebookAppId
	 **/
	@ApiModelProperty(value = "Facebook console app id.", example = "205750564737721")
	@JsonProperty("facebookAppId")
	@Field("facebook_app_id")
	@NotBlank
	private String facebookAppId;

	/**
	 * Facebook console app secret
	 * 
	 * @return facebookAppSecret
	 **/
	@ApiModelProperty(value = "Facebook console app secret", example = "85822a90153cb1850cf9d01f8ee7a119")
	@JsonProperty("facebookAppSecret")
	@Field("facebook_app_secret")
	@NotBlank
	private String facebookAppSecret;

	/**
	 * Facebook console app redirectUrl
	 * 
	 * @return facebookAppRedirectUrl
	 **/
	@ApiModelProperty(value = "Facebook console app redirectUrl", example = "http://localhost:8580/login/oauth2/code/facebook")
	@JsonProperty("facebookAppRedirectUrl")
	@Field("facebook_app_redirect_url")
	private String facebookAppRedirectUrl;

	/**
	 * Facebook console created at.
	 * 
	 * @return createdDate
	 **/
	@ApiModelProperty(value = "Facebook console created at.", example = "2017-01-13T17:09:42.411")
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
	@JsonProperty("createdDate")
	@Field("created_date")
	private LocalDateTime createdDate;

	/**
	 * Facebook console updated at.
	 * 
	 * @return updatedDate
	 **/
	@ApiModelProperty(value = "Facebook console updated at", example = "2017-01-13T17:09:42.411")
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
	@JsonProperty("updatedDate")
	@Field("updated_date")
	private LocalDateTime updatedDate;

}
