package com.oauth.security.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.validation.constraints.NotBlank;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;
import lombok.ToString;

@Document(collection = "google_console")
@lombok.Data
@ToString
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class GoogleConsole implements Serializable {
	/**
	* 
	*/
	private static final long serialVersionUID = 6192525475929778566L;
	/**
	 * Id of the GoogleConsole. Unique Id generated by the mongoDB.
	 * 
	 * @return id
	 **/
	@ApiModelProperty(value = "Id of the GoogleConsole", example = "608bfb4e1b89300008af4b76")
	@Id
	private String id;

	/**
	 * Google console updated at.
	 * 
	 * @return updatedDate
	 **/
	@ApiModelProperty(value = "ProductId of the GoogleConsole", example = "608bfb4e1b89300008af4b76")
	@JsonProperty("productId")
	@Field("productId")
	@Indexed
	@NotBlank
	private String productId;

	/**
	 * Google console app id.
	 * 
	 * @return googleAppId
	 **/
	@ApiModelProperty(value = "Google console app id.", example = "205750564737721")
	@JsonProperty("googleAppId")
	@Field("google_app_id")
	@NotBlank
	private String googleAppId;

	/**
	 * Google console app secret
	 * 
	 * @return googleAppSecret
	 **/
	@ApiModelProperty(value = "Google console app secret", example = "85822a90153cb1850cf9d01f8ee7a119")
	@JsonProperty("googleAppSecret")
	@Field("google_app_secret")
	@NotBlank
	private String googleAppSecret;

	/**
	 * Google console app redirectUrl
	 * 
	 * @return googleAppRedirectUrl
	 **/
	@ApiModelProperty(value = "Google console app redirectUrl", example = "http://localhost:8580/login/oauth2/code/google")
	@JsonProperty("googleAppRedirectUrl")
	@Field("google_app_redirect_url")
	private String googleAppRedirectUrl;

	/**
	 * Google console created at.
	 * 
	 * @return createdDate
	 **/
	@ApiModelProperty(value = "Google console created at.", example = "2017-01-13T17:09:42.411")
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
	@JsonProperty("createdDate")
	@Field("created_date")
	private LocalDateTime createdDate;

	/**
	 * Google console updated at.
	 * 
	 * @return updatedDate
	 **/
	@ApiModelProperty(value = "Google console updated at", example = "2017-01-13T17:09:42.411")
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
	@JsonProperty("updatedDate")
	@Field("updated_date")
	private LocalDateTime updatedDate;

}
