package com.oauth.security.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

import javax.validation.constraints.NotBlank;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.annotations.ApiModelProperty;
import lombok.ToString;

@Document(collection = "twitter_console")
@lombok.Data
@ToString
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class TwitterConsole implements Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 6192525475929778566L;
	/**
	 * Id of the TwitterConsole. Unique Id generated by the mongoDB.
	 * 
	 * @return id
	 **/
	@ApiModelProperty(value = "Id of the TwitterConsole", example = "608bfb4e1b89300008af4b76")
	@Id
	private String id;

	/**
	 * Twitter Console updated at.
	 * 
	 * @return updatedDate
	 **/
	@ApiModelProperty(value = "ProductId of the TwitterConsole", example = "608bfb4e1b89300008af4b76")
	@JsonProperty("productId")
	@Field("productId")
	@Indexed
	@NotBlank
	private String productId;

	/**
	 * Twitter Console consumer id.
	 * 
	 * @return googleAppId
	 **/
	@ApiModelProperty(value = " TwitterConsole consumer key.", example = "205750564737721")
	@JsonProperty("consumerKey")
	@Field("consumerKey")
	@NotBlank
	private String consumerKey;

	/**
	 * twitter console consumer secret
	 * 
	 * @return googleAppSecret
	 **/
	@ApiModelProperty(value = "Twitter console consumer secret", example = "85822a90153cb1850cf9d01f8ee7a119")
	@JsonProperty("consumerSecret")
	@Field("consumerSecret")
	@NotBlank
	private String consumerSecret;

	/**
	 * twitter console consumer secret
	 * 
	 * @return googleAppSecret
	 **/
	@ApiModelProperty(value = "Twitter console accessToken", example = "85822a90153cb1850cf9d01f8ee7a119")
	@JsonProperty("accessToken")
	@Field("accessToken")
	@NotBlank
	private String accessToken;

	/**
	 * twitter console consumer secret
	 * 
	 * @return googleAppSecret
	 **/
	@ApiModelProperty(value = "Twitter console accessTokenSecret", example = "85822a90153cb1850cf9d01f8ee7a119")
	@JsonProperty("accessTokenSecret")
	@Field("accessTokenSecret")
	@NotBlank
	private String accessTokenSecret;

	/**
	 * Twitter Console created at.
	 * 
	 * @return createdDate
	 **/
	@ApiModelProperty(value = "TwitterConsole created at.", example = "2017-01-13T17:09:42.411")
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
	@JsonProperty("createdDate")
	@Field("created_date")
	private LocalDateTime createdDate;

	/**
	 * Twitter Console updated at.
	 * 
	 * @return updatedDate
	 **/
	@ApiModelProperty(value = "TwitterConsole updated at", example = "2017-01-13T17:09:42.411")
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
	@JsonProperty("updatedDate")
	@Field("updated_date")
	private LocalDateTime updatedDate;

}
